equinor/vscode-septic

- .eslintrc.json
- .gitignore
- .vscodeignore
- README.md
- package-lock.json
- package.json
- snippets/snippets.json
- src/@types/dom.ts
- src/documentSymbolProvider.ts
- src/foldingProvider.ts
- src/tableOfContentsProvider.ts
- src/test/runTest.ts
- src/test/suite/index.ts
- tsconfig.json
Update snippets and bring toolchain + packages up to recent versions
> feat: update snippets

- .vscode/launch.json
- client/package-lock.json
- package-lock.json
- package.json
- server/package-lock.json
- server/package.json
- server/src/language-service/completionProvider.ts
- server/src/language-service/diagnosticsProvider.ts
- server/src/language-service/documentSymbolProvider.ts
- server/src/language-service/foldingRangeProvider.ts
- server/src/language-service/index.ts
- server/src/language-service/septicMetaInfoProvider.ts
- server/src/language-service/types/textDocument.ts
- server/src/parser/algParser.ts
- server/src/parser/index.ts
- server/src/parser/parser.ts
- server/src/parser/septicParser.ts
- server/src/public/septicMetaInfo.yaml
- server/src/server.ts
- server/src/util/index.ts
- server/unittest/algParser.test.ts
- server/unittest/diagnostics.test.ts
- server/unittest/folding.test.ts
- server/unittest/symbols.test.ts
- server/unittest/util/mockDocument.ts
feat: provide error reports if the calc is not parsable.
feat: provide warnings for calcs that are not supported in Septic.
feat: provide warnings for references to Xvrs that are not in the config.
feat: provide completion for (Sopc)Xvrs. Suggest existing Xvrs when creating new SopcXvr and vice versa. 
feat: provide completion of Xvrs and calcs in CalcPvr.Alg
Release-As: 1.0.0
> feat: provide diagnostics for calcs

- server/src/language-service/diagnosticsProvider.ts
Just a minor contribution from me. Feel free to merge it into your own branch, implement the fix yourself and delete this PR or whatever you prefer.
> fix: typo in error message

- README.md
- server/src/language-service/index.ts
- server/src/language-service/renameProvider.ts
- server/src/septic/septicCnfg.ts
- server/src/server.ts
- server/src/util/editBuilder.ts
> feat: add support for renaming (sopc)xvrs

- README.md
- server/src/language-service/hoverProvider.ts
- server/src/language-service/index.ts
- server/src/server.ts
> feat: add hover information on xvr-refs

- server/src/language-service/diagnosticsProvider.ts
- server/src/septic/algParser.ts
> fix: update error message for parsing of jinja in alg

- server/src/septic/algParser.ts
> fix: update error message for empty alg

- client/src/extension.ts
- client/src/util.ts
- server/src/contextManager.ts
> fix: bug with wrong files in context

- package.json
- server/src/language-service/diagnosticsProvider.ts
- server/src/septic/septicMetaInfo.ts
- server/src/server.ts
- server/src/settings.ts
> feat: add setting for updating level of calcModl

- client/src/extension.ts
- server/src/contextManager.ts
> fix: server crashing when multiple workspacefolders open

- server/src/language-service/diagnosticsProvider.ts
- server/src/test/diagnostics.test.ts
> fix: remove diagnostics on pure jinja in alg

- README.md
- package.json
- server/src/language-service/diagnosticsProvider.ts
- server/src/septic/algParser.ts
- server/src/test/diagnostics.test.ts
- snippets/snippets.json
> feat: disable diagnostics for line

- .gitignore
- client/src/test/diagnostics.test.ts
- server/src/language-service/completionProvider.ts
- server/src/language-service/diagnosticsProvider.ts
- server/src/language-service/hoverProvider.ts
- server/src/language-service/referenceProvider.ts
- server/src/public/septicMetaInfo.yaml
- server/src/septic/reference.ts
- server/src/septic/septicCnfg.ts
- server/src/septic/septicElements.ts
- server/src/septic/septicMetaInfo.ts
- server/src/septic/septicScgContext.ts
- server/src/test/diagnostics.test.ts
- server/src/test/folding.test.ts
- server/src/test/references.test.ts
- server/src/util/index.ts
- server/src/util/str.ts
> feat: add diagnostics for object attributes

- server/src/language-service/formatProvider.ts
- server/src/septic/septicElements.ts
> fix: update formatting of lists

- server/src/language-service/formatProvider.ts
> fix: formatting merging first items in list

- server/src/language-service/diagnosticsProvider.ts
> fix: no diagnostics for empty refs

- server/src/septic/septicParser.ts
- server/src/septic/septicTokens.ts
- server/src/test/septicParser.test.ts
> fix: add support for paths in msgbox.obj

- syntaxes/septic.tmLanguage.json
> fix: support syntax highlighting for oneliners

- server/src/language-service/hoverProvider.ts
- server/src/septic/septicCnfg.ts
> fix: bug with hovering in document without objects

- server/src/language-service/diagnosticsProvider.ts
- server/src/test/diagnostics.test.ts
> fix: diagnostics length bit masks

- public/calcs.yaml
- public/objectsDoc.yaml
- scripts/main.py
- scripts/src/parse_doxygen.py
- server/src/septic/docFormatting.ts
- server/src/septic/septicMetaInfo.ts
> docs: remove value from calc

- server/src/language-service/diagnosticsProvider.ts
- server/src/language-service/signatureHelpProvider.ts
- server/src/septic/algParser.ts
- server/src/test/algParser.test.ts
- server/src/test/fixtures/signatureHelp.cnfg
> refactor: improve error feedback for missing parenthesis in alg

- README.md
- server/src/language-service/completionProvider.ts
- server/src/test/completion.test.ts
- server/src/test/fixtures/completionAttrRefs.cnfg
> feat: add completion for all references to other objects

- server/src/contextManager.ts
- server/src/server.ts
> fix: clear problems on deletion of files

- server/src/language-service/diagnosticsProvider.ts
- server/src/septic/septicParser.ts
- server/src/test/diagnostics.test.ts
- syntaxes/septic.tmLanguage.json
> fix: update parsing and highlighting of invalid comments

- server/src/language-service/diagnosticsProvider.ts
- server/src/septic/reference.ts
- server/src/septic/septicCnfg.ts
- server/src/test/diagnostics.test.ts
> feat: add diagnostics for unused evrs

- server/src/septic/algParser.ts
> fix: completion of properties in calcs

- scripts/src/github.py
Auto-updating documentation did not work for documentation changes in these two files.
> ci: add missing Septic cpp files for documentation

- public/objects.yaml
- server/src/language-service/completionProvider.ts
- server/src/language-service/diagnosticsProvider.ts
- server/src/septic/septicCnfg.ts
- server/src/septic/septicMetaInfo.ts
> fix: bug with attribute references

- server/src/septic/septicCnfg.ts
> fix: clipped references in lists

- server/src/language-service/diagnosticsProvider.ts
- server/src/septic/algParser.ts
Closes #477 
Requires update of relevant calc documentation
> fix: support non-xvr calc params

- server/src/language-service/diagnosticsProvider.ts
- server/src/test/diagnostics.test.ts
> fix: bug with unnecessary diagnostics for pure jinja in calcs that expect value

- server/src/septic/septicParser.ts
- server/src/test/fixtures/formatting/uncompletedJinjaExpected.cnfg
- server/src/test/fixtures/formatting/uncompletedJinjaOriginal.cnfg
- server/src/test/format.test.ts
> fix: deleting code when formatting uncomplete jinja

- server/src/language-service/completionProvider.ts
- server/src/test/completion.test.ts
> fix: autocomplete for variables containing jinja

- server/src/language-service/formatProvider.ts
> fix: formatting of jinja right after attribute def

- server/src/language-service/cycleReportProvider.ts
- server/src/septic/cycle.ts
- server/src/test/cycle.test.ts
> fix: support setmeas in cycle detection

- client/src/extension.ts
- client/src/protocol.ts
- package.json
- server/src/language-service/index.ts
- server/src/language-service/opctagListProvider.ts
- server/src/protocol.ts
- server/src/septic/reference.ts
- server/src/septic/septicCnfg.ts
- server/src/septic/septicScgContext.ts
- server/src/server.ts
> feat: add command for extracting opctags to csv

- public/latest/meta.yaml
- public/latest/objectsDoc.yaml
- public/latest/snippets.yaml
- scripts/src/parse_doxygen.py
- server/src/septic/septicMetaInfo.ts
- server/src/test/diagnostics.test.ts
> fix: error parsing object documentation and snippets

- server/src/language-service/diagnosticsProvider.ts
- server/src/test/diagnostics.test.ts
> feat: add diagnostics for duplicate xvr identifiers

- server/src/septic/septicParser.ts
> fix: parsing of jinja code with modulus operator

- server/src/language-service/completionProvider.ts
- server/src/language-service/diagnosticsProvider.ts
- server/src/language-service/hoverProvider.ts
- server/src/language-service/index.ts
- server/src/language-service/opctagListProvider.ts
- server/src/language-service/referenceProvider.ts
- server/src/septic/reference.ts
- server/src/septic/septicCnfg.ts
- server/src/septic/septicElements.ts
- server/src/test/completion.test.ts
- server/src/test/diagnostics.test.ts
> fix: add support for opcua objects

- .github/workflows/codequality.yml
- README.md
- client/src/extension.ts
- client/src/protocol.ts
- package.json
- public/defaultComparisonSetting.yaml
- server/src/language-service/cnfgComparisonProvider.ts
- server/src/language-service/index.ts
- server/src/protocol.ts
- server/src/septic/algParser.ts
- server/src/server.ts
- server/src/test/compareCnfg.test.ts
> feat: add command for comparing cnfgs

- server/src/language-service/diagnosticsProvider.ts
- server/src/septic/calc.ts
- server/src/test/diagnostics.test.ts
> fix: diagnostics for calcs with fixed number of params at end

- server/src/septic/septicCnfg.ts
- server/src/test/references.test.ts
- server/src/util/str.ts
> feat: support refs in algs with jinja for and if

- server/src/language-service/codeActionProvider.ts
- server/src/server.ts
> fix: failed code action

- package.json
- server/src/language-service/completionProvider.ts
- server/src/language-service/index.ts
- server/src/septic/reference.ts
- server/src/septic/septicCnfg.ts
- server/src/septic/septicScgContext.ts
- server/src/settings.ts
- server/src/test/completion.test.ts
- server/src/test/diagnostics.test.ts
Might be annoying when you want to prototype something fast.
> feat: suggest snippets based on object hierarchy

- server/src/language-service/diagnosticsProvider.ts
- server/src/test/diagnostics.test.ts
> fix: wrong diagnostic message for xvrs using public properties

- client/package-lock.json
- client/package.json
- package-lock.json
- package.json
- server/package-lock.json
- server/package.json
> fix: update import of js-yaml

- server/src/septic/septicCnfg.ts
- server/src/test/references.test.ts
- server/src/util/str.ts
> fix: extraction of refs in jinja calc

- client/src/test/completion.test.ts
- server/src/language-service/completionProvider.ts
> fix: add priority to Mvrs and Cvrs in autocomplete

- server/src/language-service/cnfgComparisonProvider.ts
> fix: path to default compare config

- server/src/language-service/diagnosticsProvider.ts
- server/src/septic/septicMetaInfo.ts
> fix: error in loading param datatypes documentation
